import { useEffect, type ReactNode } from 'react';
import type { DataSourceKind } from '../../core/types';
import { useToasts } from '../state/toasts';

export function Modal({ title, onClose, children, footer, wide }: { title: ReactNode; onClose: () => void; children: ReactNode; footer?: ReactNode; wide?: boolean }) {
  useEffect(() => {
    const k = (e: KeyboardEvent) => e.key === 'Escape' && onClose();
    window.addEventListener('keydown', k);
    return () => window.removeEventListener('keydown', k);
  }, [onClose]);
  return (
    <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
      <div className={`modal${wide ? ' wide' : ''}`} role="dialog" aria-modal="true">
        <div className="modal-head">
          <h2>{title}</h2>
          <div className="spacer" />
          <button className="btn ghost icon" onClick={onClose} aria-label="Close">
            ✕
          </button>
        </div>
        <div className="modal-body">{children}</div>
        {footer && <div className="modal-foot">{footer}</div>}
      </div>
    </div>
  );
}

export function EmptyState({ title, children }: { title: string; children?: ReactNode }) {
  return (
    <div className="empty">
      <h3>{title}</h3>
      {children}
    </div>
  );
}

const SOURCE_TEXT: Record<DataSourceKind, string> = {
  LIVE: 'LIVE DATA',
  HISTORICAL: 'HISTORICAL DATA',
  DEMO: 'DEMO DATA · SYNTHETIC',
  SIMULATED: 'SIMULATED · FICTIONAL',
};

export const SOURCE_EXPLAIN: Record<DataSourceKind, string> = {
  LIVE: 'Real-time prices from a market-data vendor.',
  HISTORICAL: 'Real recorded market data (your CSV import or a vendor API), replayed with no look-ahead.',
  DEMO: 'Synthetic bars bundled for offline use. They behave like real tape but are NOT the real prices of these tickers on these dates.',
  SIMULATED: 'A fictional market generated by a stochastic model. Companies, prices and news are made up.',
};

export function SourceBadge({ source, title }: { source: DataSourceKind; title?: boolean }) {
  return (
    <span className={`badge ${source}`} title={title === false ? undefined : SOURCE_EXPLAIN[source]}>
      <span className="dot" />
      {SOURCE_TEXT[source]}
    </span>
  );
}

export function Toasts() {
  const { toasts, dismiss } = useToasts();
  return (
    <div className="toasts" aria-live="polite">
      {toasts.map((t) => (
        <div key={t.id} className={`toast ${t.tone}`} onClick={() => dismiss(t.id)}>
          {t.text}
        </div>
      ))}
    </div>
  );
}

export function Stat({ k, v, cls }: { k: string; v: ReactNode; cls?: string }) {
  return (
    <div className="stat">
      <div className="k">{k}</div>
      <div className={`v ${cls ?? ''}`}>{v}</div>
    </div>
  );
}

export function NumberField({
  label,
  value,
  onChange,
  step,
  min,
  max,
  suffix,
  disabled,
}: {
  label: string;
  value: number | '';
  onChange: (v: number | '') => void;
  step?: number;
  min?: number;
  max?: number;
  suffix?: string;
  disabled?: boolean;
}) {
  return (
    <label className="field">
      <span>
        {label}
        {suffix ? <span className="muted"> ({suffix})</span> : null}
      </span>
      <input
        type="number"
        value={value}
        step={step}
        min={min}
        max={max}
        disabled={disabled}
        onChange={(e) => onChange(e.target.value === '' ? '' : Number(e.target.value))}
      />
    </label>
  );
}
