import { useEffect, useId, useRef, type ReactNode } from 'react';
import type { DataSourceKind } from '../../core/types';
import { useToasts } from '../state/toasts';

/** Open modals, innermost last. Only the topmost one reacts to Escape and traps Tab. */
const modalStack: string[] = [];

/** True while any modal dialog is open (global shortcuts stand down). */
export function modalOpen(): boolean {
  return modalStack.length > 0;
}

const FOCUSABLE = 'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

export function Modal({ title, onClose, children, footer, wide }: { title: ReactNode; onClose: () => void; children: ReactNode; footer?: ReactNode; wide?: boolean }) {
  const id = useId();
  const dialogRef = useRef<HTMLDivElement>(null);
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;
  // Read during the first render, before anything inside the dialog takes focus.
  const openerRef = useRef<HTMLElement | null | undefined>(undefined);
  if (openerRef.current === undefined) openerRef.current = document.activeElement as HTMLElement | null;

  useEffect(() => {
    modalStack.push(id);
    const opener = openerRef.current;
    const dialog = dialogRef.current!;
    // Focus moves into the dialog, to the control marked data-autofocus if there is one, so Tab
    // starts inside and Space or Enter acts on the dialog rather than on the page behind it.
    if (!dialog.contains(document.activeElement)) (dialog.querySelector<HTMLElement>('[data-autofocus]') ?? dialog).focus();
    const onKey = (e: KeyboardEvent) => {
      if (modalStack[modalStack.length - 1] !== id) return;
      if (e.key === 'Escape') {
        onCloseRef.current();
      } else if (e.key === 'Tab') {
        const items = [...dialog.querySelectorAll<HTMLElement>(FOCUSABLE)].filter((el) => el.offsetParent !== null);
        if (!items.length) return;
        const first = items[0];
        const last = items[items.length - 1];
        if (e.shiftKey && (document.activeElement === first || document.activeElement === dialog)) {
          e.preventDefault();
          last.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    };
    window.addEventListener('keydown', onKey);
    return () => {
      window.removeEventListener('keydown', onKey);
      modalStack.splice(modalStack.indexOf(id), 1);
      // Give focus back to whatever opened the dialog, if it is still on the page.
      if (opener && opener.isConnected && typeof opener.focus === 'function') opener.focus();
    };
  }, [id]);

  return (
    <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
      <div ref={dialogRef} className={`modal${wide ? ' wide' : ''}`} role="dialog" aria-modal="true" aria-labelledby={`${id}-title`} tabIndex={-1}>
        <div className="modal-head">
          <h2 id={`${id}-title`}>{title}</h2>
          <div className="spacer" />
          <button className="btn ghost icon" onClick={onClose} aria-label="Close">
            ✕
          </button>
        </div>
        <div className="modal-body">{children}</div>
        {footer && <div className="modal-foot">{footer}</div>}
      </div>
    </div>
  );
}

export function EmptyState({ title, children }: { title: string; children?: ReactNode }) {
  return (
    <div className="empty">
      <h3>{title}</h3>
      {children}
    </div>
  );
}

const SOURCE_TEXT: Record<DataSourceKind, string> = {
  LIVE: 'LIVE DATA',
  HISTORICAL: 'HISTORICAL DATA',
  DEMO: 'DEMO DATA · SYNTHETIC',
  SIMULATED: 'SIMULATED · FICTIONAL',
};

export const SOURCE_EXPLAIN: Record<DataSourceKind, string> = {
  LIVE: 'Real-time prices from a market-data vendor.',
  HISTORICAL: 'Real recorded market data (your CSV import or a vendor API), replayed with no look-ahead.',
  DEMO: 'Synthetic bars bundled for offline use. They behave like real tape but are NOT the real prices of these tickers on these dates.',
  SIMULATED: 'A fictional market generated by a stochastic model. Companies, prices and news are made up.',
};

export function SourceBadge({ source, title }: { source: DataSourceKind; title?: boolean }) {
  return (
    <span className={`badge ${source}`} title={title === false ? undefined : SOURCE_EXPLAIN[source]}>
      <span className="dot" />
      {SOURCE_TEXT[source]}
    </span>
  );
}

export function Toasts() {
  const { toasts, dismiss } = useToasts();
  return (
    <div className="toasts" aria-live="polite">
      {toasts.map((t) => (
        <div key={t.id} className={`toast ${t.tone}`} onClick={() => dismiss(t.id)}>
          {t.text}
        </div>
      ))}
    </div>
  );
}

export function Stat({ k, v, cls }: { k: string; v: ReactNode; cls?: string }) {
  return (
    <div className="stat">
      <div className="k">{k}</div>
      <div className={`v ${cls ?? ''}`}>{v}</div>
    </div>
  );
}

export function NumberField({
  label,
  value,
  onChange,
  step,
  min,
  max,
  suffix,
  disabled,
}: {
  label: string;
  value: number | '';
  onChange: (v: number | '') => void;
  step?: number;
  min?: number;
  max?: number;
  suffix?: string;
  disabled?: boolean;
}) {
  return (
    <label className="field">
      <span>
        {label}
        {suffix ? <span className="muted"> ({suffix})</span> : null}
      </span>
      <input
        type="number"
        value={value}
        step={step}
        min={min}
        max={max}
        disabled={disabled}
        onChange={(e) => onChange(e.target.value === '' ? '' : Number(e.target.value))}
      />
    </label>
  );
}
